name: Build SignalRGB Editor

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Create app files
      run: |
        # 创建 package.json
        echo '{
          "name": "signalrgb-editor",
          "version": "1.0.0",
          "main": "main.js",
          "scripts": {
            "build": "electron-builder"
          },
          "devDependencies": {
            "electron": "^28.0.0",
            "electron-builder": "^24.0.0"
          },
          "build": {
            "appId": "com.signalrgb.editor",
            "productName": "SignalRGB编辑器",
            "directories": {
              "output": "dist"
            },
            "files": ["main.js", "index.html"],
            "win": {
              "target": "nsis"
            }
          }
        }' > package.json
        
        # 创建 main.js
        echo 'const { app, BrowserWindow } = require("electron");
        function createWindow() {
          const win = new BrowserWindow({
            width: 1600,
            height: 1000,
            webPreferences: {
              nodeIntegration: false,
              contextIsolation: true
            },
            title: "SignalRGB设备模型编辑器"
          });
          win.loadFile("index.html");
        }
        app.whenReady().then(createWindow);
        app.on("window-all-closed", () => {
          if (process.platform !== "darwin") app.quit();
        });' > main.js
    
    - name: Install and build
      run: |
        npm install
        npm run build
    
    - uses: actions/upload-artifact@v4
      with:
        name: SignalRGB-Editor
        path: dist/
